apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: jh
type: Opaque
data:
  secret: TnpnME4yWXpNVE5tTnpjNFlUWTFaams1WkRRME5qRTJZV0kwTUdGaU9EYzFZbVE1TURnM09EUXpZMlU0WkRKak56TTBObVl6T0RrMFpERXhNakpsWkRBNE1qWTNOVFE0TVdRNE5qRmxZVFF4TXpGbE56UTJOalExTnpGbU9EbGlPRGxtTnc9PQ==
